- name: crete docker context
  file:
    state: directory
    path: "{{ mirror_context }}"

- name: copy repo files to mirror_context
  copy:
    src: /tmp/yum.repos.d/
    dest: "{{ mirror_context }}"

- name: generate Dockerfile
  template:
    src: build-mirror-Dockerfile.j2
    dest: "{{ mirror_context }}/Dockerfile"

- name: copy reposync script
  copy:
    src: mirro-repo.py
    dest: "{{ mirror_context }}/mirror-repo.py"

- name: generate config command
  template:
    src: build-mirror-config.sh.j2
    dest: "{{ mirror_context }}/config.sh"

- name: copy starter command
  copy:
    src: build-mirror-start.sh
    dest: "{{ mirror_context }}/start.sh"

- name: Build mirror container
  docker_image:
    name: repo-mirror:latest
    state: present
    path: "{{ mirror_context }}"

- name: Generate docker-registry env
  template:
    src: docker-registry.yaml.j2
    dest: {{ working_dir }}/docker-registry.yaml

- name: start repo mirror container
   docker_container:
    name: repo-mirror
    image: repo-mirror
    restart: yes
    env:
      host_ip: {{ ansible_br_ctlplane.ipv4.address }}
      system_repofiles_path: {{ system_repofiles_path }}
      mirror_repofiles_path: {{ mirror_path }}
      mirror_port: {{ mirro_port }}
    ports:
      - "{{ mirror_port }}:{{ mirror_port }}"

# variables for kolla build
#- name: Retrieve the real trunk repository configuration
#  shell: >
#    curl -L {{ trunk_repository }} |awk -F= '/baseurl/ {print $2}'
#  register: baseurl

#- name: Define hashed repository variables
#  set_fact:
#    version_hash: "{{ baseurl.stdout.split('/')[-1] }}"
#    hashed_trunk_repository: "{{ baseurl.stdout }}/delorean.repo"

